### ISSUE TITLE
lowercase json keys

### ISSUE THREAD

**Issue by jbenet** [whyrusleeping/gx#3]
to be npm package.json compatible, the json keys must be lowercase. 

now, it outputs uppercase:

```sh
> gx init
initializing package go-multiaddr...
> cat package.json
{
  "Name": "go-multiaddr",
  "Files": null,  // omit 
  "Version": "",
  "Dependencies": null,   // should be {}
  "Bin": "", // omit
  "Build": "", // omit
  "Test": "", // omit
  "Language": "" // omit
}
```

also want to:
- omit empty keys. 
- _always_ have a version

**Comment by whyrusleeping** [comment]
> - *always* have a version

should version have a default value? and should publish autoincrement the patch version if nothing else changed since the previous publish?

**Comment by travisperson** [comment]
On a `npm init` npm will give you `1.0.0` if you do not specify something different.

> should publish autoincrement the patch version if nothing else changed since the previous publish?

I think so, forcing a patch update is probably a good thing. Versions should be tied to a hash, and that hash should never change. It someone screwed something up they can publish a new patch.

See a bit of discussion here https://github.com/npm/npm-registry-couchapp/issues/148

**Comment by diasdavid** [comment]
@whyrusleeping I typically use https://www.npmjs.com/package/npm-release to publish my npm modules, it is a really nifty tool because not only takes care of doing the right version bump (`npm-release [patch, minor, major]`) but also makes sure it is commited to github and creates a tag with the release. Would love if this became part of the feature set of gx :)

**Comment by diasdavid** [comment]
> omit empty keys.

npm is ok with empty keys, and I kind of like them as a reminder. But that is just my opinion :)
